# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FC6bTj1wdD9cKSBtTq4EZxE_tnKSSVXc
"""

! pip install streamlit

import streamlit as st
import pickle
import numpy as np

# -----------------------
# Load Model & Vectorizer
# -----------------------
@st.cache_resource
def load_model():
    with open("model.pkl", "rb") as file:
        model = pickle.load(file)
    with open("vectorizer.pkl", "rb") as file:
        vectorizer = pickle.load(file)
    return model, vectorizer

model, vectorizer = load_model()


# -----------------------
# Streamlit Page Config
# -----------------------
st.set_page_config(
    page_title="News Sentiment Classification",
    page_icon="📰",
    layout="wide",
    initial_sidebar_state="expanded"
)


# -----------------------
# Sidebar Section
# -----------------------
st.sidebar.title("⚙️ App Controls")
st.sidebar.info(
    """
    **News Sentiment Classification App**
    Analyze if a news headline is **Positive** or **Negative**
    using a trained **Multinomial Naive Bayes** model.

    **Files Loaded:**
    ✓ model.pkl
    ✓ vectorizer.pkl
    """
)
st.sidebar.markdown("---")
st.sidebar.write("Developed by **Your Name**")


# -----------------------
# Title and Description
# -----------------------
st.title("📰 News Sentiment Classification Dashboard")
st.write(
    """
    This application uses a **Multinomial Naive Bayes model + TF-IDF** to classify
    the sentiment of news headlines or news text.
    """
)

st.markdown("---")


# -----------------------
# Input Section
# -----------------------
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("🔍 Enter News Text")
    user_input = st.text_area(
        "Type or paste a news headline here:",
        height=150,
        placeholder="Example: 'Stock market rises after positive economic report'"
    )

with col2:
    st.subheader("📊 Dashboard Info")
    st.metric("Model Type", "Multinomial Naive Bayes")
    st.metric("Vectorizer", "TF-IDF (bigrams)")
    st.metric("Classes", "Positive / Negative")


# -----------------------
# Prediction
# -----------------------
if st.button("Analyze Sentiment", use_container_width=True):
    if user_input.strip() == "":
        st.warning("⚠️ Please enter some news text before predicting.")
    else:
        # Transform input using vectorizer
        input_tf = vectorizer.transform([user_input])

        # Predict sentiment (0 = negative, 1 = positive)
        prediction = model.predict(input_tf)[0]

        # Prediction probability
        prob = np.max(model.predict_proba(input_tf))

        # Nice UI display
        st.markdown("---")
        st.subheader("🧠 Model Prediction")

        if prediction == 1:
            st.success(f"### 🟢 Sentiment: **Positive**  \nProbability: `{prob:.2f}`")
        else:
            st.error(f"### 🔴 Sentiment: **Negative**  \nProbability: `{prob:.2f}`")

        st.markdown("---")

        # Display confidence bar
        st.subheader("📈 Prediction Confidence")
        st.progress(prob)

        st.markdown("---")

        # Extra section
        st.info(
            """
            ✅ This model is optimized for short news texts
            📌 Uses TF-IDF with bigrams (1–2 word combinations)
            🧠 Trained using Multinomial Naive Bayes
            """
        )