# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FC6bTj1wdD9cKSBtTq4EZxE_tnKSSVXc
"""


import streamlit as st
import joblib
import numpy as np

# Load model & vectorizer
model = joblib.load("sentiment_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

# ---- Page Config ----
st.set_page_config(
    page_title="News Sentiment Classifier",
    page_icon="📰",
    layout="centered",
)

# ---- Custom CSS ----
st.markdown("""
<style>
body {
    background-color: #f2f4f7;
    font-family: 'Segoe UI', sans-serif;
}

.card {
    background-color: #ffffff;
    padding: 30px;
    border-radius: 16px;
    box-shadow: 0px 5px 25px rgba(0,0,0,0.06);
}

.result-box {
    padding: 18px;
    border-radius: 12px;
    text-align: center;
    font-size: 24px;
    font-weight: 650;
    margin-top: 15px;
}

.positive { background-color: #d4edda; color: #155724; border-left: 6px solid #28a745; }
.negative { background-color: #f8d7da; color: #721c24; border-left: 6px solid #dc3545; }
.neutral  { background-color: #fff3cd; color: #856404; border-left: 6px solid #ffc107; }

textarea {
    border-radius: 10px !important;
}
</style>
""", unsafe_allow_html=True)

# ---- Main Heading ----
st.markdown("<h1 style='text-align:center;'>📰 News Sentiment Classifier</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center; color:#666; margin-top:-10px;'>Analyze the sentiment of any news headline in seconds</p>", unsafe_allow_html=True)

# ---- Card Container ----
st.markdown("<div class='card'>", unsafe_allow_html=True)

# Text Input
text_input = st.text_area(
    "Enter a News Headline",
    placeholder="Example: 'Stock markets rise after new economic reforms'",
    height=120
)

# Predict button
btn = st.button("Analyze Sentiment", use_container_width=True)

# ---- Prediction Logic ----
if btn:
    if text_input.strip() == "":
        st.warning("⚠️ Please enter a news headline.")
    else:
        vec = vectorizer.transform([text_input])
        pred = model.predict(vec)[0]

        # UI result box (same logic)
        if pred == "positive":
            color_class = "positive"
            label = "Positive 🔥"
        elif pred == "negative":
            color_class = "negative"
            label = "Negative ⚠️"
        else:
            color_class = "neutral"
            label = "Neutral 🟡"

        st.markdown(
            f"<div class='result-box {color_class}'>{label}</div>",
            unsafe_allow_html=True
        )

# Close card
st.markdown("</div>", unsafe_allow_html=True)
